Functional test for RHBZ1473203 and some adjustments
apahim/qemu pull request #9
Opened 2017-08-06 13:20 UTC by ldoktor

This PR adjusts a bit the "get_console" handling and adds functional test for RHBZ1473203.

2017-08-07 09:43 UTC, apahim commented on tests/avocado/avocado_qemu/test.py
> +    session.sendline()
ok

2017-08-07 09:44 UTC, apahim commented on tests/avocado/avocado_qemu/test.py
> +                 r"(?<![Ll]ast )[Ll]ogin:\s*",  # Don't match "Last Login:"
Sure. And this can always be improved if we face new corner cases.

2017-08-07 09:45 UTC, apahim commented on tests/avocado/rhbz1473203_numa_hotplug.py
> +    Fixed in commit kernel commit dc421b200f91930c9c6a9586810ff8c232cf10fc.
commit kernel commit

2017-08-07 09:49 UTC, apahim commented on tests/avocado/rhbz1473203_numa_hotplug.py
> +        self.vm.shutdown()
This test requires a vm image. I'd include both the parameters.yaml file and the instructions to use it.

2017-08-07 09:52 UTC, apahim requested changes
@ldoktor just a minor fix in the docstring. Also, I'd include the parameters.yaml since this test requires a VM image. (or some other way to indicate that).

2017-08-24 14:18 UTC, ldoktor commented
OK, updated. There is yet another batch of fixes to `get_console`, change to default params and not insignificant changes to the functional test make it less-error-prone.

2017-08-24 14:46 UTC, apahim commented on tests/avocado/test_nec-usb-xhci.py
> +        self.require_image()
self.request_image()

2017-08-24 14:59 UTC, ldoktor commented on tests/avocado/test_nec-usb-xhci.py
> +        self.require_image()
sure, sorry I added it on a last minute... I'll fix it in v2

2017-08-24 15:00 UTC, apahim commented on tests/avocado/test_nec-usb-xhci.py
> +        self.require_image()
no need for v2. I'm handling that while integrating your commits.

2017-08-24 15:34 UTC, apahim commented
All merged.

2017-08-24 15:34 UTC, closed without merging